<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="1" total="7" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="103" started-at="2016-07-03T05:19:12Z" finished-at="2016-07-03T05:19:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="103" started-at="2016-07-03T05:19:12Z" finished-at="2016-07-03T05:19:12Z">
      <class name="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest">
        <test-method status="PASS" signature="initializeTestCases()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="initializeTestCases" is-config="true" duration-ms="15" started-at="2016-07-03T00:19:12Z" finished-at="2016-07-03T00:19:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestCases -->
        <test-method status="FAIL" signature="testCreate()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testCreate" duration-ms="50" started-at="2016-07-03T00:19:12Z" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testCreate(QuoteDAOTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreate -->
        <test-method status="SKIP" signature="testSaveNoLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testSaveNoLineItems" duration-ms="0" started-at="2016-07-03T00:19:12Z" depends-on-methods="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testCreate" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method QuoteDAOTest.testSaveNoLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method QuoteDAOTest.testSaveNoLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSaveNoLineItems -->
        <test-method status="SKIP" signature="testFindByIdentifier()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testFindByIdentifier" duration-ms="0" started-at="2016-07-03T00:19:12Z" depends-on-methods="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testSaveNoLineItems" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method QuoteDAOTest.testFindByIdentifier()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method QuoteDAOTest.testFindByIdentifier()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindByIdentifier -->
        <test-method status="SKIP" signature="testFindAllQuotes()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testFindAllQuotes" duration-ms="0" started-at="2016-07-03T00:19:12Z" depends-on-methods="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testSaveNoLineItems, com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testFindByIdentifier" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method QuoteDAOTest.testFindAllQuotes()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method QuoteDAOTest.testFindAllQuotes()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindAllQuotes -->
        <test-method status="SKIP" signature="testQuoteLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testQuoteLineItems" duration-ms="0" started-at="2016-07-03T00:19:12Z" depends-on-methods="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testFindAllQuotes" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method QuoteDAOTest.testQuoteLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method QuoteDAOTest.testQuoteLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testQuoteLineItems -->
        <test-method status="SKIP" signature="testQuoteLineItemSave()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testQuoteLineItemSave" duration-ms="0" started-at="2016-07-03T00:19:12Z" depends-on-methods="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testQuoteLineItems" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method QuoteDAOTest.testQuoteLineItemSave()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method QuoteDAOTest.testQuoteLineItemSave()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testQuoteLineItemSave -->
        <test-method status="SKIP" signature="testCorrectLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5]" test-instance-name="" name="testCorrectLineItems" duration-ms="0" started-at="2016-07-03T00:19:12Z" depends-on-methods="com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testQuoteLineItemSave, com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest.testQuoteLineItems" finished-at="2016-07-03T00:19:12Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method QuoteDAOTest.testCorrectLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method QuoteDAOTest.testCorrectLineItems()[pri:0, instance:com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest@92260b5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCorrectLineItems -->
      </class> <!-- com.wildstartech.wfa.dao.logistics.ltl.QuoteDAOTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
